using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DV.Glimmer.UI;

[GenerateTypedNameReferences]
public sealed partial class GlimmerNavMapWindow : FancyWindow
{
    public GlimmerNavMapWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetMapUid(EntityUid? gridUid)
    {
        NavMap.MapUid = gridUid;
        NavMap.ForceNavMapUpdate();
    }
}
